spring:
  application:
    name: asa-demo
  cloud:
    config:
      name: asa-test
      profile: prod
  profiles:
    active: dev
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
management:
  endpoints:
    web:
      exposure:
        include: '*'