spring:
  application:
    name: asa-demo
  cloud:
    config:
      name: asa-test
      profile: prod
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'